# Generated by Django 5.1 on 2024-11-18 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALUMRUT', models.CharField(max_length=12)),
                ('ALUMNOMBRE', models.CharField(max_length=15)),
                ('ALUMAPATERNO', models.CharField(max_length=15)),
                ('ALUMAMATERNO', models.CharField(max_length=15)),
                ('ALUMDIRECCION', models.CharField(max_length=60)),
                ('ALUMEMAIL', models.CharField(max_length=40)),
                ('ALUMFONO', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIUCODIGO', models.IntegerField(max_length=6)),
                ('CIUNOMBRE', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipocurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPCURCODIGO', models.IntegerField(max_length=6)),
                ('TIPCURNOMBRE', models.CharField(max_length=20)),
                ('TIPCURVALOR', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USULOGIN', models.CharField(max_length=15)),
                ('USUPASSWORD', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUCCODIGO', models.IntegerField(max_length=6)),
                ('SUCNOMBRE', models.CharField(max_length=20)),
                ('CIUCODIGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prueba.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MATNUMERO', models.IntegerField(max_length=11)),
                ('MATFECHA', models.DateField()),
                ('ALUMRUT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prueba.alumnos')),
                ('SUCCODIGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prueba.sucursales')),
                ('TIPCURCODIGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prueba.tipocurso')),
            ],
        ),
    ]
