# Generated by Django 5.1 on 2024-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
