# Generated by Django 5.0.4 on 2024-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sueldo', models.IntegerField()),
            ],
        ),
    ]
